(() => {
  'use strict';
  const E=window.NumericEngine, original=E.clone(window.NUMERIC_DATA), $=id=>document.getElementById(id), colors={'绿':'#7cbb8d','蓝':'#78b6ee','紫':'#c795e3','金':'#e6bd6e'};
  let data=E.clone(original),state,mode=localStorage.getItem('music-numeric-mode')||'trial',history=[],future=[],dragId=null,previousTotal=null,rewardFolded=false,toastTimer,pointerDrag=null,suppressClickUntil=0,rewardSelection=null,rewardIndex=null,stagePlaying=false; 
  const key=m=>'music-numeric-20260914-'+m;
  try{const saved=JSON.parse(localStorage.getItem('music-numeric-config'));if(saved){validateData(saved);data=saved;data.items.forEach(i=>i.icon=original.items.find(o=>o.id===i.id).icon);}}catch{}
  function validateData(d){if(d.items?.length!==31||!d.rules||d.rules.rows!==7||d.rules.cols!==7)throw Error('配置须包含31件道具及7×7棋盘');
    const ids=new Set();for(const item of d.items){if(ids.has(item.id)||!original.items.some(i=>i.id===item.id))throw Error('道具ID无效或重复');ids.add(item.id);if(item.base.length!==6||item.effect.length!==3||[...item.base,...item.effect].some(v=>!Number.isFinite(v)||v<0))throw Error('道具数值须为非负有限数值，基础6档、技能3档');const src=original.items.find(i=>i.id===item.id);if(item.width!==src.width||item.height!==src.height)throw Error('宽高和图标路径须保持原配置');}
    for(const k of ['drawStamina','unlockStamina','unlockCells','advancedEvery','duplicatesPerLevel','woodDivisor','beatMin','beatMax'])if(!Number.isInteger(d.rules[k])||d.rules[k]<=0)throw Error(k+'须为正整数');
    if(d.rules.beatMax<d.rules.beatMin||d.rules.beatMax>100||d.rules.maxLevel!==6)throw Error('节拍范围或等级不正确');
    for(const k of ['normalWeights','advancedWeights','beatWeights'])if(d.rules[k].length!==4||d.rules[k].some(x=>!Number.isFinite(x)||x<0)||d.rules[k].reduce((a,b)=>a+b,0)<=0)throw Error('概率权重无效');
    if(!['percent','fixed'].includes(d.rules.woodMode)||!['hits','generated'].includes(d.rules.woodCount))throw Error('木琴参数无效');
    if(d.rules.initialRows!==3||d.rules.initialCols!==3)throw Error('当前验证版初始区域固定3×3');if(!Array.isArray(d.rules.beatRates)||d.rules.beatRates.length!==4||d.rules.beatRates.some(row=>row.length!==3||row.some(n=>!Number.isFinite(n)||n<0)))throw Error('节拍加成须为4品质×3判定的非负数值');
    for(const k of ['charmCap','charmExponent','charmScale','targetRatio'])if(!Number.isFinite(d.rules[k])||d.rules[k]<0||(k==='targetRatio'&&d.rules[k]===0))throw Error('魅力参数无效');
  }
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=n=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:3}),pct=n=>num(n*100)+'%';
  const item=id=>data.items.find(i=>i.id===id), snapshot=()=>E.clone(state);
  function effectDescription(i,level=1){const value=i.effect[E.tierIndex(level)];if(i.id==='P23')return `表演结算时，每${data.rules.woodDivisor}个${data.rules.woodCount==='hits'?'成功点击':'生成'}节拍，获得${value}${data.rules.woodMode==='percent'?'个百分点节拍加成':'点固定分数'}；向下取整，不消耗节拍。`;return i.description.replaceAll('a点',num(value)+'点').replaceAll('a%',pct(value)).replaceAll('x个',num(value)+'个');}
  function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,2600);}
  function save(){localStorage.setItem(key(mode),JSON.stringify(state));localStorage.setItem('music-numeric-mode',mode);localStorage.setItem('music-numeric-config',JSON.stringify(data));}
  function loadMode(next){mode=next;try{state=JSON.parse(localStorage.getItem(key(mode)));if(!state||state.version!==data.version)throw Error();for(const [id,o] of Object.entries(state.owned))if(!item(id)||o.level<1||o.level>6)throw Error();}catch{state=E.newState(data,mode);}history=[];future=[];previousTotal=null;rewardFolded=false;render();}
  function checkpoint(){history.push(snapshot());if(history.length>60)history.shift();future=[];}
  function locked(){if(stagePlaying){toast('请先完成表演');return true;}if(state.drawQueue.length){toast('请先完成三选一；可先使用扩格额度');return true;}return false;}
  function image(i,cls=''){return `<img class="prop-icon ${cls}" src="${esc(i.icon)}" alt="${esc(i.name)}" draggable="false">`;}
  function footprint(i){return `<span class="footprint" role="img" aria-label="占格预览：${i.width}列${i.height}行，共${i.width*i.height}格" title="${i.width}列 × ${i.height}行，共${i.width*i.height}格，不可旋转" style="--cols:${i.width};--rows:${i.height}">${'<i></i>'.repeat(i.width*i.height)}</span>`;}
  function render(){const p=E.score(state,data);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));
    $('metrics').innerHTML=[['剩余体力',num(state.stamina),`已消耗 ${state.spent}`],['累计表演值',num(state.scoreSum),`${state.shows} 场`],['开放格子',state.unlocked.length+'/49',`可解锁 ${state.unlockCredits} 格`],['抽奖次数',state.drawCount,`待选 ${state.drawQueue.length} 次`],['已拥有道具',Object.keys(state.owned).length+'/31',mode==='test'?'自由验证':'成长体验'],['累计效率',num(state.spent?state.scoreSum/state.spent:0),'分/体力']].map(([a,b,c])=>`<div class="metric"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('');
    $('score').textContent=num(p.total);$('delta').textContent=previousTotal!==null&&p.total!==previousTotal?`本次变化 ${p.total-previousTotal>0?'+':''}${num(p.total-previousTotal)}`:'';
    $('breakdown').innerHTML=[['基础演奏值',p.base],['成员套装',p.member],['道具能力',p.ability],['全局固定值',p.globalFixed],['全局百分比',pct(p.globalPercent)]].map(([a,b])=>`<span>${a}<b>${typeof b==='number'?num(b):b}</b></span>`).join('');
    const occupied=state.placed.reduce((a,q)=>a+item(q.id).width*item(q.id).height,0);$('spaceSummary').textContent=`已放 ${state.placed.length} 件 · 占用 ${occupied} / ${state.unlocked.length} 格 · ${state.unlockCredits} 格待解锁`;
    $('sets').innerHTML=p.sets.map(s=>`<button class="set-pill ${s.tier?'on':''}" data-set="${esc(s.name)}" title="${esc(setText(s))}">${s.name} ${s.count}件${s.tier?' · '+(s.index+1)+'档':''}</button>`).join('');
    $('sets').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('setFilter').value=b.dataset.set;renderInventory();});
    renderBoard(p);renderInventory();renderDetail(p);
    $('drawProgress').innerHTML=`抽奖体力 ${state.drawRemainder}/${data.rules.drawStamina} · 第${state.drawCount+1}次${(state.drawCount+1)%data.rules.advancedEvery===0?'高级':'普通'}<progress max="${data.rules.drawStamina}" value="${state.drawRemainder}"></progress>`;
    const full=state.unlocked.length+state.unlockCredits>=49;$('unlockProgress').innerHTML=`${full?'扩格额度已全部发放':`扩格体力 ${state.unlockRemainder}/${data.rules.unlockStamina} · 下次＋${data.rules.unlockCells}格`}<progress max="${data.rules.unlockStamina}" value="${full?data.rules.unlockStamina:state.unlockRemainder}"></progress>`;
    $('perform').disabled=state.drawQueue.length>0;$('undo').disabled=!history.length||state.drawQueue.length>0;$('redo').disabled=!future.length||state.drawQueue.length>0;$('expandAll').disabled=!state.unlockCredits;
    $('resumeReward').hidden=!state.drawQueue.length||!rewardFolded;renderReward();save();
  }
  function setText(s){return s.tiers.map(t=>`${s.exact?'恰好':'至少'}${t[0]}件：${s.type==='percent'?pct(t[1]):'+'+t[1]}${s.type==='member'?' / 成员演奏值':s.type==='perMember'?' × 成员数 / 背包表演值':''}`).join('；')+(s.type==='rock'?'；6件档每件打击乐额外+5':s.type==='folk'?'；4件档额外+成员总等级×3':'');}
  function renderBoard(p){const b=$('board');b.innerHTML='';const selected=p.info[state.selected];
    for(let c=0;c<49;c++){const open=state.unlocked.includes(c),test={...state,unlocked:[...state.unlocked]};let can=false;if(!open&&state.unlockCredits)can=E.unlock(test,data,c);const el=document.createElement('button');el.className=`cell ${open?'open':''} ${can?'expandable':''}`;el.style.gridColumn=String(c%7+1);el.style.gridRow=String(Math.floor(c/7)+1);el.dataset.cell=c;el.textContent=open?'':can?'+':'·';el.title=`第${Math.floor(c/7)+1}行，第${c%7+1}列${open?'':can?'：点击解锁':'：锁定'}`;el.onclick=()=>{if(!open){if(E.unlock(state,data,c)){history=[];future=[];render();}else toast('先获得扩格额度，再点击与开放区相邻的格子');}else if(state.selected)place(state.selected,c%7,Math.floor(c/7));};b.append(el);}
    for(const q of state.placed){const i=item(q.id),v=p.info[q.id],el=document.createElement('button');el.className=`piece ${state.selected===q.id?'selected':''} ${selected?.matches.includes(q.id)?'source-match':''} ${selected?.targets.includes(q.id)?'effect-target':''}`;el.dataset.id=q.id;el.style.setProperty('--quality',colors[i.quality]);el.style.gridColumn=`${q.x+1} / span ${i.width}`;el.style.gridRow=`${q.y+1} / span ${i.height}`;el.draggable=false;el.innerHTML=image(i)+footprint(i)+`<span class="label"><span>${i.name}</span><b>${num(v.total)}</b></span>`;el.title=`${i.name} ${state.owned[i.id].level}级 · ${i.width}×${i.height} · Ctrl点击卸下`;el.onclick=e=>{if(e.ctrlKey)unplace(q.id);else{state.selected=q.id;render();}};el.onpointerdown=e=>beginDrag(e,q.id,el);el.ondragstart=e=>e.preventDefault();b.append(el);}
  }
  function beginDrag(e,id,source){if(e.button!==0||e.ctrlKey||pointerDrag)return;pointerDrag={id,source,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,started:false,ghost:null,candidate:null};source.setPointerCapture?.(e.pointerId);document.addEventListener('pointermove',moveDrag);document.addEventListener('pointerup',endDrag);document.addEventListener('pointercancel',cancelDrag);}
  function moveDrag(e){const d=pointerDrag;if(!d||d.pointerId!==e.pointerId)return;if(!d.started){if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)<5)return;if(locked()){cancelDrag();return;}d.started=true;dragId=d.id;state.selected=d.id;const i=item(d.id),cell=$('board').querySelector('.cell').getBoundingClientRect(),gap=parseFloat(getComputedStyle($('board')).columnGap)||0;d.ghost=document.createElement('div');d.ghost.className='drag-preview pointer-ghost';d.ghost.style.cssText=`width:${cell.width*i.width+gap*(i.width-1)}px;height:${cell.height*i.height+gap*(i.height-1)}px;--quality:${colors[i.quality]};--cols:${i.width};--rows:${i.height};--gap:${gap}px`;d.ghost.innerHTML=`<span class="drag-grid">${'<i></i>'.repeat(i.width*i.height)}</span>${image(i)}<span class="drag-name">${i.name} · ${i.width}×${i.height}</span>`;document.body.append(d.ghost);d.source.classList.add('dragging-source');}e.preventDefault();updateDrag(e.clientX,e.clientY);}
  function updateDrag(clientX,clientY){const d=pointerDrag,i=item(d.id),board=$('board'),r=board.getBoundingClientRect(),cell=board.querySelector('.cell').getBoundingClientRect(),gap=parseFloat(getComputedStyle(board).columnGap)||0;d.ghost.style.transform=`translate(${clientX}px,${clientY}px)`;clearDrop();d.candidate=null;const over=clientX>=cell.left&&clientX<r.right&&clientY>=cell.top&&clientY<r.bottom;if(over){const x=Math.floor((clientX-cell.left)/(cell.width+gap)),y=Math.floor((clientY-cell.top)/(cell.height+gap));const verdict=E.placement(state,data,d.id,x,y),valid=verdict.valid;d.candidate={x,y,...verdict};if(valid)previewDragEffects(d.id,x,y,verdict.swapId);for(let dy=0;dy<i.height;dy++)for(let dx=0;dx<i.width;dx++){if(x+dx>=0&&x+dx<7&&y+dy>=0&&y+dy<7)board.querySelector(`[data-cell="${(y+dy)*7+x+dx}"]`)?.classList.add(valid?'drop-ok':'drop-bad');}d.ghost.classList.toggle('invalid',!valid);d.ghost.classList.toggle('swap',valid&&!!verdict.swapId);d.ghost.querySelector('.drag-name').textContent=verdict.swapId&&valid?`替换${item(verdict.swapId).name} → 回仓`:i.name+' · '+i.width+'×'+i.height;}else{const w=document.querySelector('.inventory-panel').getBoundingClientRect(),returning=state.placed.some(p=>p.id===d.id)&&clientX>=w.left&&clientX<w.right&&clientY>=w.top&&clientY<w.bottom;d.candidate=returning?{warehouse:true}:null;document.querySelector('.inventory-panel').classList.toggle('drop-active',returning);d.ghost.classList.toggle('invalid',!returning);}}
  function endDrag(e){const d=pointerDrag;if(!d||d.pointerId!==e.pointerId)return;if(d.started){updateDrag(e.clientX,e.clientY);const candidate=d.candidate;cleanupDrag();suppressClickUntil=Date.now()+350;if(candidate?.warehouse)unplace(d.id);else if(candidate?.valid)place(d.id,candidate.x,candidate.y);else toast('未放入有效空格，道具保留原位置');}else cleanupDrag();}
  function cleanupDrag(){const d=pointerDrag;pointerDrag=null;document.removeEventListener('pointermove',moveDrag);document.removeEventListener('pointerup',endDrag);document.removeEventListener('pointercancel',cancelDrag);if(d?.source.hasPointerCapture?.(d.pointerId))d.source.releasePointerCapture(d.pointerId);d?.source.classList.remove('dragging-source');d?.ghost?.remove();document.querySelector('.inventory-panel').classList.remove('drop-active');clearDrop();dragId=null;}
  function cancelDrag(){if(pointerDrag?.started)suppressClickUntil=Date.now()+350;cleanupDrag();}
  document.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation();}},true);
  window.addEventListener('blur',cancelDrag);
  function clearDrop(){document.querySelectorAll('.drop-ok,.drop-bad,.drag-target,.drag-source').forEach(e=>e.classList.remove('drop-ok','drop-bad','drag-target','drag-source'));}
  function place(id,x,y){if(!id||!state.owned[id]||locked())return;const verdict=E.placement(state,data,id,x,y);if(!verdict.valid){toast('无法放置：越界、未解锁或同时覆盖多件道具');return;}checkpoint();previousTotal=E.score(state,data).total;state.placed=state.placed.filter(p=>p.id!==id&&p.id!==verdict.swapId);state.placed.push({id,x,y});state.selected=id;render();if(verdict.swapId)toast(item(verdict.swapId).name+'已回仓');}
  function unplace(id){if(locked())return;checkpoint();previousTotal=E.score(state,data).total;state.placed=state.placed.filter(p=>p.id!==id);render();}
  function autoPlace(id){for(let y=0;y<7;y++)for(let x=0;x<7;x++)if(E.validPlacement(state,data,id,x,y)){place(id,x,y);return;}toast('没有足够的连续空间；道具不可旋转');}
  function renderInventory(){const query=$('search').value.trim(),quality=$('quality').value,category=$('category').value,set=$('setFilter').value;const filtered=data.items.filter(i=>(state.owned[i.id]||mode==='test')&&(!query||[i.name,i.id,i.category,i.song].join(' ').includes(query))&&(!quality||i.quality===quality)&&(!category||i.category===category)&&(!set||i.category===set||i.song===set));
    $('inventorySummary').textContent=`${Object.keys(state.owned).length} 件已拥有 · 选中后拖放或点击格子`;
    $('inventory').innerHTML=filtered.map(i=>`<button class="inventory-item ${state.selected===i.id?'selected':''}" style="--quality:${colors[i.quality]}" data-id="${i.id}" draggable="false">${image(i)}<span><strong>${i.name}</strong><small>${i.quality} · ${i.width}×${i.height} · ${state.owned[i.id]?.level||1}级${state.placed.some(p=>p.id===i.id)?' · 在场':''}</small><small>${i.category}${i.song?' / '+i.song:''}</small>${footprint(i)}</span></button>`).join('')||'<p class="hint">没有符合条件的道具</p>';
    $('inventory').querySelectorAll('[data-id]').forEach(b=>{b.onclick=e=>{state.selected=b.dataset.id;if(e.ctrlKey)autoPlace(state.selected);else render();};b.onpointerdown=e=>beginDrag(e,b.dataset.id,b);b.ondragstart=e=>e.preventDefault();});
  }
  function renderDetail(p){const i=item(state.selected);if(!i){$('detail').innerHTML='<p>选择道具，查看每级数值、计数来源和受益目标。</p>';return;}const o=state.owned[i.id],level=o?.level||1,v=p.info[i.id];const description=effectDescription(i,level);
    $('detail').innerHTML=`<div class="detail-head"><h3>${i.name}</h3>${footprint(i)}<span style="color:${colors[i.quality]}">${i.quality} · ${i.width}×${i.height} · 不可旋转</span></div><p>${esc(description).replaceAll('a点',num(i.effect[E.tierIndex(level)])+'点').replaceAll('a%',pct(i.effect[E.tierIndex(level)]))}</p><div class="numbers">${i.base.map((b,j)=>`<div class="${level===j+1?'current':''}"><small>${j+1}级</small><b>${num(b)}</b></div>`).join('')}</div><p>实际效果（1／3／6级）：${i.effect.map(n=>i.category==='装扮'?pct(n):num(n)).join(' / ')}${i.id==='P21'?'（生成上限）':''}</p>${i.notes.length?`<div class="note">${i.notes.map(esc).join('；')}</div>`:''}${i.id==='P23'?'<div class="note">木琴转换参数为测试口径，可在参数面板调整。</div>':''}${v?`<div class="formula">本件演奏值：${v.base} + 套装 ${num(v.member)} + 能力 ${num(v.ability)} = ${num(v.total)}</div><div class="sources">条件计数：${v.count}；${v.active?'已生效':'当前未触发'}<br>匹配来源：${v.matches.map(id=>item(id).name).join('、')||'无'}<br>受益目标：${v.targets.map(id=>item(id).name).join('、')||'背包／资源或无'}<br>${v.sources.map(s=>`${s.type} · ${s.name} +${num(s.value)}`).join('<br>')}</div>`:'<p>当前在仓库，不参与任何结算。</p>'}<div class="detail-actions">${mode==='test'?`<label>测试等级 <select id="level">${[1,2,3,4,5,6].map(n=>`<option ${level===n?'selected':''}>${n}</option>`).join('')}</select></label>`:`<span>升级进度 ${o?.progress||0}/${data.rules.duplicatesPerLevel}</span>`}<button id="quickPlace">${v?'卸回仓库':'自动找空位'}</button><button id="editItem">调整测试数值</button></div><p class="hint">来源：${i.source}；青色为条件来源，绿色为受益目标。</p>`;
    const preview=document.createElement('div');preview.className='detail-preview';preview.innerHTML=image(i);$('detail').querySelector('.detail-head').after(preview);const actionBar=$('detail').querySelector('.detail-actions');$('detail').querySelector('.detail-head').after(actionBar);
    if($('level'))$('level').onchange=e=>{if(locked())return;checkpoint();previousTotal=p.total;o.level=Number(e.target.value);o.progress=0;render();};$('quickPlace').onclick=()=>v?unplace(i.id):autoPlace(i.id);$('editItem').onclick=()=>editItem(i.id);
  }
  function modal(title,html){$('modalTitle').textContent=title;$('modalContent').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
  function editItem(id){if(locked())return;const i=item(id);modal('调整测试数值 · '+i.name,`<p>只修改本机数值版；原始Excel不变。保存后立即重算。</p><h3>各级基础演奏值</h3><div class="form-grid">${i.base.map((n,j)=>`<label>${j+1}级<input id="base${j}" type="number" min="0" step="any" value="${n}"></label>`).join('')}</div><h3>实际效果</h3><div class="form-grid">${i.effect.map((n,j)=>`<label>${[1,3,6][j]}级档${i.category==='装扮'?'（小数比例）':''}<input id="effect${j}" type="number" min="0" step="any" value="${n}"></label>`).join('')}</div><p class="hint">2级沿用1级，4～5级沿用3级。</p><button class="primary" id="saveItem">保存并重算</button>`);$('saveItem').onclick=()=>{const base=i.base.map((_,j)=>Number($('base'+j).value)),effect=i.effect.map((_,j)=>Number($('effect'+j).value));if([...base,...effect].some(x=>!Number.isFinite(x)||x<0)){toast('请输入非负数');return;}i.base=base;i.effect=effect;i.notes=['当前使用手动测试值'];history=[];future=[];$('modal').close();render();};}
  function renderReward(){const q=state.drawQueue[0];if(q?.index!==rewardIndex){rewardSelection=null;rewardIndex=q?.index;}if(!q){if($('reward').open)$('reward').close();$('resumeReward').hidden=true;return;}if(rewardFolded)return;
    $('rewardTitle').textContent=`第${q.index}次 · ${q.advanced?'高级':'普通'}三选一`;$('rewardSummary').textContent=`剩余${state.drawQueue.length}次待选 · ${state.unlockCredits}格可解锁 · ${q.advanced?'紫85% / 金15%':'绿67.5% / 蓝25% / 紫7.5%'}（每个选项独立抽取）`;
    $('choices').innerHTML=q.choices.map(id=>{const i=item(id),o=state.owned[id];return `<button class="choice ${rewardSelection===id?'selected':''}" aria-pressed="${rewardSelection===id}" data-id="${id}" style="--quality:${colors[i.quality]}">${image(i)}<div>${footprint(i)}<h3>${i.name}</h3><small>${i.quality} · ${i.width}×${i.height} · ${i.category}</small><small>${i.song||'无乐曲归属'}</small><p>${esc(effectDescription(i,o?.level||1))}</p><small>${o?o.level===6?'已满级；本次不增加等级':`已拥有${o.level}级 · 获得后增加1份升级进度`:'新道具 · 1级'}</small></div></button>`;}).join('');$('choices').querySelectorAll('button').forEach(b=>b.onclick=()=>{rewardSelection=b.dataset.id;renderReward();});$('confirmReward').disabled=!rewardSelection;$('rewardSelection').textContent=rewardSelection?'已选：'+item(rewardSelection).name:'请选择一件道具';$('confirmReward').onclick=()=>{if(!rewardSelection)return;const id=rewardSelection,msg=E.choose(state,data,id);state.selected=id;history=[];future=[];toast(item(id).name+'：'+msg);render();};if(!$('reward').open)$('reward').showModal();
  }
  function showResult(result){modal('本场表演结果',`<div class="score" style="text-align:left"><strong>${num(result.total)}</strong><span>最终表演值</span></div><p>${result.baseBeats}基础节拍 ＋ ${result.extraBeats}架子鼓节拍，共${result.totalBeats}个；成功${result.hits}个</p><div class="formula">${esc(result.formula)}</div><table><tr><th>组成</th><th>本场结果</th></tr><tr><td>背包表演值</td><td>${num(result.preview)}</td></tr><tr><td>节拍操作加成</td><td>${pct(result.beatRate)}</td></tr><tr><td>木琴转换</td><td>${result.woodGroups}组 → ${data.rules.woodMode==='percent'?pct(result.woodPercent):num(result.woodFixed)+'分'}</td></tr><tr><td>魅力加成</td><td>${pct(result.charm)}</td></tr></table><p class="hint">种子：${esc(result.seed)}。按单场计算得分；消耗体力数影响奖励进度，不自动倍乘本场分数。</p><button id="continueResult" class="primary">继续${state.drawQueue.length?'三选一':'配置'}</button>`);$('continueResult').onclick=()=>{$('modal').close();rewardFolded=false;render();};}
  async function perform(){if(locked())return;if(!state.placed.length){toast('请先放入道具');return;}const amount=Number($('cost').value);try{if(!Number.isInteger(amount)||amount<=0||amount>state.stamina)throw Error('体力不足或消耗值不是正整数');const seed=`${state.seed}:show:${state.shows+1}`,opts={seed,judgment:$('judgment').value,beats:$('beats').value===''?null:Number($('beats').value),charmRatio:state.charmRatio||0};let result=E.performance(state,data,opts);if(!$('skipStage').checked){stagePlaying=true;const judgments=await playStage(result);stagePlaying=false;if(!judgments){toast('已取消表演，未消耗体力');return;}result=E.performance(state,data,{...opts,judgments});}E.spend(state,data,amount);state.shows++;state.scoreSum+=result.total;state.logs.unshift({...result,number:state.shows,stamina:amount,spent:state.spent});if(state.logs.length>1000)state.logs.pop();history=[];future=[];rewardFolded=true;render();showResult(result);}catch(e){stagePlaying=false;toast(e.message);}}
  function tools(){if(locked())return;modal('参数与规则',`<p>数值表最终结果＋已确认规则。此处修改仅保存到本机。</p><div class="form-grid"><label>剩余体力<input id="editStamina" type="number" min="0" value="${state.stamina}"></label><label>可复现种子<input id="editSeed" value="${esc(state.seed)}"></label><label>魅力之和 / 服务器战力<input id="charmRatio" type="number" min="0" step="any" value="${state.charmRatio||0}"></label><label>木琴每组节拍数<input id="woodDivisor" type="number" min="1" value="${data.rules.woodDivisor}"></label><label>木琴转换结果<select id="woodMode"><option value="percent" ${data.rules.woodMode==='percent'?'selected':''}>每组增加百分比百分点</option><option value="fixed" ${data.rules.woodMode==='fixed'?'selected':''}>每组增加固定分数</option></select></label><label>木琴计数来源<select id="woodCount"><option value="generated" ${data.rules.woodCount==='generated'?'selected':''}>生成节拍数</option><option value="hits" ${data.rules.woodCount==='hits'?'selected':''}>成功点击数</option></select></label></div><p><button class="primary" id="saveTools">保存参数</button> <button id="recover">模拟恢复30分钟体力</button> <button id="allCells">测试：开放全部49格</button></p><h3>已采用规则</h3><table><tr><td>棋盘</td><td>7×7；初始中央3×3；道具固定宽高，不可旋转</td></tr><tr><td>扩格</td><td>累计消耗5体力发放2格额度；只解锁与开放区相邻的格子；满49格停止</td></tr><tr><td>抽奖</td><td>累计消耗3体力一次三选一；7次普通后第8次高级；每个选项独立抽品质</td></tr><tr><td>概率</td><td>普通：绿67.5%、蓝25%、紫7.5%；高级：紫85%、金15%</td></tr><tr><td>升级</td><td>同名唯一；每2个重复道具升1级；最高6级；满级重复不再成长</td></tr><tr><td>技能档位</td><td>1～2级 / 3～5级 / 6级；空缺能力使用可编辑测试值</td></tr><tr><td>位置条件</td><td>相邻：上下左右接边；方向：同轴投影条带，不限距离；不同种类按五种乐器分类去重，装扮不计入乐器</td></tr><tr><td>连续相邻</td><td>沿管乐相邻链查找；实例去重，不跨不匹配乐器</td></tr><tr><td>套装</td><td>最高满足档；优雅晚宴按至少1/4件；键盘恰好1件；摇滚按件；民族按总等级</td></tr><tr><td>背包公式</td><td>floor((基础＋成员固定值＋道具固定值＋全局固定值) × (1＋全局百分比))</td></tr><tr><td>表演公式</td><td>floor(背包表演值 × (1＋节拍加成＋木琴百分比＋魅力加成)＋木琴固定值)</td></tr><tr><td>魅力加成</td><td>min(20%, ((魅力之和/服务器战力)/0.0189)^0.8 × 0.09)</td></tr></table><h3>套装结果</h3>${data.sets.map(s=>`<p><b>${s.name}</b>：${setText(s)}</p>`).join('')}<h3>案例与存档</h3><p><button data-preset="guzheng">古筝计数案例</button> <button data-preset="chain">萨克斯连续链</button> <button data-preset="beats">架子鼓＋木琴</button></p><p><button id="exportState">导出布局与参数</button> <label><button id="importStateButton">载入布局与参数</button><input id="importState" type="file" accept=".json" hidden></label> <button id="resetMode">重置当前模式</button></p><p class="hint">案例切换到自由验证模式，并保留成长体验存档。原始Excel和旧版demo均不会被覆盖。</p>`);
    addTools();
    $('saveTools').onclick=()=>{const stamina=Number($('editStamina').value),charm=Number($('charmRatio').value),divisor=Number($('woodDivisor').value);if(!Number.isInteger(stamina)||stamina<0||!Number.isFinite(charm)||charm<0||!Number.isInteger(divisor)||divisor<1){toast('输入值无效');return;}state.stamina=stamina;state.seed=$('editSeed').value||'music';state.charmRatio=charm;data.rules.woodDivisor=divisor;data.rules.woodMode=$('woodMode').value;data.rules.woodCount=$('woodCount').value;history=[];future=[];$('modal').close();render();};
    $('recover').onclick=()=>{state.stamina=state.stamina>=data.rules.staminaCap?state.stamina:Math.min(data.rules.staminaCap,state.stamina+data.rules.recoverAmount);$('editStamina').value=state.stamina;save();toast('已模拟一次体力恢复');};
    $('allCells').onclick=()=>{if(mode!=='test'){toast('请切换自由验证模式后使用');return;}checkpoint();state.unlocked=Array.from({length:49},(_,i)=>i);state.unlockCredits=0;state.unlockRemainder=0;$('modal').close();render();};
    $('exportState').onclick=()=>download('爱乐之城-数值验证存档.json',JSON.stringify({data,state},null,2),'application/json');$('importStateButton').onclick=()=>$('importState').click();$('importState').onchange=importState;
    $('resetMode').onclick=()=>{if(!confirm('重置当前模式的摆放、体力和抽奖进度？'))return;state=E.newState(data,mode);history=[];future=[];$('modal').close();render();};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset));toolTabs();
  }
  function toolTabs(){const content=$('modalContent'),children=[...content.children],panes=['模拟与Excel','参数','规则与套装','案例与存档'].map(()=>{const el=document.createElement('section');el.className='tool-pane';return el;});let target=1;for(const child of children){if(child.classList.contains('extra-tools')){panes[0].append(child);continue;}if(child.tagName==='H3'&&child.textContent==='已采用规则')target=2;if(child.tagName==='H3'&&child.textContent==='案例与存档')target=3;panes[target].append(child);}const tabs=document.createElement('nav');tabs.className='tool-tabs';['模拟与Excel','参数','规则与套装','案例与存档'].forEach((label,n)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{panes.forEach((p,i)=>p.hidden=i!==n);[...tabs.children].forEach((c,i)=>c.classList.toggle('active',i===n));};tabs.append(b);});content.append(tabs,...panes);tabs.children[1].click();}
  function previewDragEffects(id,x,y,swapId){const test=E.clone(state);test.placed=test.placed.filter(p=>p.id!==id&&p.id!==swapId);test.placed.push({id,x,y});const v=E.score(test,data).info[id];for(const p of $('board').querySelectorAll('.piece')){p.classList.toggle('drag-source',v.matches.includes(p.dataset.id));p.classList.toggle('drag-target',v.targets.includes(p.dataset.id));}}
  function playStage(plan){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='live-stage';dialog.innerHTML=`<div class="modal-top"><h2>现场表演</h2><button id="cancelStage">取消</button></div><p>共${plan.totalBeats}拍（基础${plan.baseBeats}＋架子鼓${plan.extraBeats}） · 在中央亮区点击或按空格</p><div class="spotlight" id="stageInstrument"></div><p id="liveBeat"></p><div class="rhythm-track"><span class="good-zone"></span><span class="great-zone"></span><span class="perfect-zone"></span><i id="liveMarker"></i></div><button class="primary rhythm-hit" id="hitBeat">点击合拍 / 空格</button><p id="liveFeedback">准备开始</p><div class="stage-history" id="stageHistory"></div><div class="actions"><button id="stageSpeed">速度 ×1</button><button id="skipRest">跳过剩余（按所选判定模拟）</button></div><p class="hint">判定窗口为体验测试值：距离中心≤8% Perfect、≤18% Great、≤32% Good，其余Miss。道具与节拍品质按当前数值配置。</p>`;document.body.append(dialog);dialog.showModal();let index=0,progress=0,last=performance.now(),speed=1,frame,ended=false,awaiting=false,pauseUntil=last+500;const judgments=[],props=state.placed.map(p=>item(p.id));const get=id=>dialog.querySelector('#'+id);
    const cleanup=result=>{if(ended)return;ended=true;cancelAnimationFrame(frame);document.removeEventListener('keydown',key);dialog.close();dialog.remove();resolve(result);};
    const showBeat=()=>{const i=props[index%props.length];get('stageInstrument').innerHTML=image(i)+`<strong>${i.name}</strong>`;get('liveBeat').textContent=`第${index+1}/${plan.totalBeats}拍 · 节拍品质${plan.beatResults[index].quality}`;};
    const finishBeat=judgment=>{if(ended||awaiting)return;awaiting=true;judgments.push(judgment);get('liveFeedback').textContent=judgment;get('stageHistory').textContent=judgments.join(' · ');get('hitBeat').disabled=true;pauseUntil=performance.now()+300/speed;};
    const hit=()=>{if(!awaiting&&performance.now()>=pauseUntil)finishBeat(E.judgeTiming(progress));};const key=e=>{if(e.code==='Space'){e.preventDefault();hit();}};document.addEventListener('keydown',key);get('hitBeat').onclick=hit;get('cancelStage').onclick=()=>cleanup(null);dialog.oncancel=e=>{e.preventDefault();cleanup(null);};get('stageSpeed').onclick=()=>{speed=speed===1?2:1;get('stageSpeed').textContent='速度 ×'+speed;};get('skipRest').onclick=()=>{while(judgments.length<plan.totalBeats)judgments.push(plan.beatResults[judgments.length].judgment);cleanup(judgments);};showBeat();
    const tick=now=>{if(ended)return;const delta=Math.min(now-last,80);last=now;if(now>=pauseUntil){if(awaiting){index++;if(index>=plan.totalBeats){cleanup(judgments);return;}progress=0;awaiting=false;showBeat();get('hitBeat').disabled=false;}else{progress+=delta*speed/1500;get('liveMarker').style.left=Math.min(100,progress*100)+'%';if(progress>=1)finishBeat('Miss');}}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
  });}
  function addTools(){const content=$('modalContent'),extra=document.createElement('section');extra.className='extra-tools';extra.innerHTML=`<h3>批量模拟</h3><p>模拟不消耗体力、不改变布局和抽奖进度；同一种子可复现。</p><div class="form-grid"><label>种子<input id="batchSeed" value="${esc(state.seed)}"></label><label>场次<input id="batchCount" type="number" min="1" max="1000" value="100"></label><label>每场消耗（效率分母）<input id="batchCost" type="number" min="1" value="${Number($('cost').value)||1}"></label></div><p><button id="runBatch" class="primary">运行模拟</button> <button data-count="1">1场</button> <button data-count="100">100场</button> <button data-count="1000">1000场</button> <button id="batchCsv" disabled>导出结果</button></p><div id="batchOutput"></div><h3>Excel配置</h3><p>可加载原《A爱乐之城.xlsx》最终结果，或本验证器导出的数值模板。全部校验通过后才会应用，不重算测算区。</p><p><button id="exportExcel">导出数值Excel</button> <button id="loadExcel">加载数值Excel</button><input id="excelFile" type="file" accept=".xlsx" hidden></p><p class="hint">旧V2的48件配置结构不同，不直接混入当前31件奖池。指定解锁格数为验证工具，会清空当前扩格额度，缩小区域时相关道具回仓。</p>`;content.prepend(extra);let batch=[];
    $('runBatch').onclick=()=>{try{const count=Number($('batchCount').value),cost=Number($('batchCost').value),seed=$('batchSeed').value||'batch';if(!Number.isInteger(count)||count<1||count>1000||!Number.isInteger(cost)||cost<1)throw Error('场次须为1～1000，消耗须为正整数');if(!state.placed.length)throw Error('请先摆放道具');batch=Array.from({length:count},(_,i)=>E.performance(state,data,{seed:`${seed}:batch:${i+1}`,judgment:$('judgment').value,beats:$('beats').value===''?null:Number($('beats').value),charmRatio:state.charmRatio||0}));const values=batch.map(r=>r.total).sort((a,b)=>a-b),sum=values.reduce((a,b)=>a+b,0);$('batchOutput').textContent=`${count}场 · 总分 ${num(sum)} · 均值 ${num(sum/count)} · 最低 ${values[0]} · 最高 ${values.at(-1)} · P50 ${values[Math.floor((count-1)*.5)]} · 平均效率 ${num(sum/count/cost)}分/体力`;$('batchCsv').disabled=false;}catch(e){toast(e.message);}};extra.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{$('batchCount').value=b.dataset.count;$('runBatch').click();});$('batchCsv').onclick=()=>download('批量模拟.csv','种子,背包值,总分,节拍数,节拍加成\r\n'+batch.map(r=>[JSON.stringify(r.seed),r.preview,r.total,r.totalBeats,r.beatRate].join(',')).join('\r\n'),'text/csv');$('exportExcel').onclick=exportExcel;$('loadExcel').onclick=()=>$('excelFile').click();$('excelFile').onchange=loadExcel;
  }
  function exportExcel(){const wb=XLSX.utils.book_new(),add=(name,rows)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),name);add('道具',[['ID','名称','1级基础','2级基础','3级基础','4级基础','5级基础','6级基础','1级效果','3级效果','6级效果'],...data.items.map(i=>[i.id,i.name,...i.base,...i.effect])]);add('规则',[['字段','值(JSON格式)'],...Object.entries(data.rules).map(([k,v])=>[k,JSON.stringify(v)])]);add('套装',[['名称','档位(JSON格式)'],...data.sets.map(s=>[s.name,JSON.stringify(s.tiers)])]);add('说明',[['只填最终结果；不含测算区'],['效果为1/3/6档，2级沿用1级，4/5级沿用3级'],['装扮效果为小数比例，如0.003；木琴为百分点，如1'],['保持ID和31件数量；资源路径与形状由当前配置确定']]);XLSX.writeFile(wb,'爱乐之城-数值验证配置.xlsx');}
  async function loadExcel(e){try{if(!e.target.files[0])return;const wb=XLSX.read(await e.target.files[0].arrayBuffer(),{type:'array'}),candidate=readNumericWorkbook(wb);validateData(candidate);if(candidate.sets.length!==10||candidate.sets.some(s=>!Array.isArray(s.tiers)||s.tiers.some(t=>t.length!==2||!Number.isInteger(t[0])||t[0]<1||!Number.isFinite(t[1])||t[1]<0)))throw Error('套装档位无效');data=candidate;history=[];future=[];$('modal').close();render();toast('Excel最终结果已载入');}catch(error){toast('加载失败：'+error.message);}}
  function readNumericWorkbook(wb){const out=E.clone(data),val=(sheet,cell)=>{const v=wb.Sheets[sheet]?.[cell]?.v;if(typeof v!=='number'||!Number.isFinite(v)||v<0)throw Error(sheet+'!'+cell+'缺少有效结果');return v;};
    if(wb.Sheets['道具']){const rows=XLSX.utils.sheet_to_json(wb.Sheets['道具'],{header:1}).slice(1).filter(r=>r[0]),seen=new Set();if(rows.length!==31)throw Error('必须包含31件道具');for(const r of rows){const i=out.items.find(i=>i.id===r[0]);if(!i||seen.has(i.id)||r[1]!==i.name)throw Error('道具ID或名称不匹配');seen.add(i.id);i.base=r.slice(2,8);i.effect=r.slice(8,11);i.notes=['从数值Excel载入'];}if(!wb.Sheets['规则']||!wb.Sheets['套装'])throw Error('缺少规则或套装页');const ruleRows=XLSX.utils.sheet_to_json(wb.Sheets['规则'],{header:1}).slice(1).filter(r=>r[0]),keys=new Set();for(const [key,value] of ruleRows){if(!(key in out.rules)||keys.has(key))throw Error('规则字段无效/重复');keys.add(key);out.rules[key]=JSON.parse(String(value));}if(keys.size!==Object.keys(out.rules).length)throw Error('规则字段不完整');const sets=XLSX.utils.sheet_to_json(wb.Sheets['套装'],{header:1}).slice(1).filter(r=>r[0]);if(sets.length!==10||new Set(sets.map(r=>r[0])).size!==10)throw Error('套装数量/名称重复');for(const [name,tiers] of sets){const set=out.sets.find(s=>s.name===name);if(!set)throw Error('套装名称不匹配');set.tiers=JSON.parse(tiers);}return out;}
    if(!wb.Sheets['乐器设计']||!wb.Sheets['数值设计'])throw Error('不支持此Excel结构，请使用数值模板或A爱乐之城.xlsx');const ws=wb.Sheets['乐器设计'];for(const i of out.items){const rows=XLSX.utils.sheet_to_json(ws,{header:1});const matches=rows.map((r,n)=>({r,n:n+1})).filter(({r})=>r[1]===i.name&&r[4]===i.height&&r[5]===i.width);if(matches.length!==1)throw Error(i.name+'名称/占格未唯一匹配');const row=matches[0].n;i.base=['K','L','M','N','O','P'].map(c=>val('乐器设计',c+row));if(i.description!=='无额外能力'){const effects=['AF','AG','AH'].map(c=>ws[c+row]?.v);if(effects.every(v=>typeof v==='number'&&v>=0))i.effect=effects;else if(!['P08','P21'].includes(i.id))throw Error(i.name+'实际效果缺值');}if(i.id==='P21')i.effect=[5,5,5];}
    const mapping={rows:'S12',cols:'S13',initialRows:'S7',initialCols:'S8',initialStamina:'E8',staminaCap:'E9',recoverAmount:'E11',beatMin:'AN22',beatMax:'AO22',charmCap:'AN4',charmExponent:'AN5',charmScale:'AN6',targetRatio:'AN8'};for(const [key,c] of Object.entries(mapping))out.rules[key]=val('数值设计',c);out.rules.recoverMinutes=val('数值设计','E10')*60;out.rules.advancedEvery=val('数值设计','AC14')+1;out.rules.normalWeights=['AB','AC','AD','AE'].map(c=>val('数值设计',c+'17'));out.rules.advancedWeights=['AB','AC','AD','AE'].map(c=>val('数值设计',c+'18'));out.rules.beatWeights=[25,26,27,28].map(r=>val('数值设计','AN'+r));out.rules.beatRates=[25,26,27,28].map(r=>['AO','AP','AQ'].map(c=>val('数值设计',c+r)));
    const setRows=[108,109,110,111,112,115,116,117,118,119];out.sets.forEach((set,n)=>{const desc=String(ws['J'+setRows[n]]?.v||''),groups=[...desc.matchAll(/增加\s*([\d.]+(?:\/[\d.]+)*)/g)].map(m=>m[1].split('/').map(Number)),values=groups.flat();if(values.length<set.tiers.length)throw Error(set.name+'结果描述无法识别');set.tiers=set.tiers.map((t,j)=>[t[0],values[j]/(set.type==='percent'?100:1)]);});return out;
  }

  function preset(name){save();mode='test';state=E.newState(data,mode);state.unlocked=Array.from({length:49},(_,i)=>i);state.placed=name==='guzheng'?[{id:'P16',x:2,y:2},{id:'P11',x:2,y:1},{id:'P12',x:2,y:4},{id:'P13',x:0,y:6}]:name==='chain'?[{id:'P04',x:0,y:0},{id:'P01',x:2,y:0},{id:'P02',x:2,y:1},{id:'P06',x:2,y:3}]:[{id:'P21',x:2,y:2},{id:'P23',x:1,y:4},{id:'P11',x:2,y:1},{id:'P07',x:0,y:2},{id:'P01',x:4,y:2},{id:'P22',x:4,y:3}];state.selected=name==='guzheng'?'P16':name==='chain'?'P04':'P21';history=[];future=[];$('modal').close();render();}
  async function importState(e){try{const v=JSON.parse((await e.target.files[0].text()).replace(/^\uFEFF/,""));validateData(v.data);const st=v.state;if(!['trial','test'].includes(st.mode)||!Array.isArray(st.unlocked)||new Set(st.unlocked).size!==st.unlocked.length||st.unlocked.some(c=>!Number.isInteger(c)||c<0||c>=49))throw Error('存档棋盘无效');for(const [id,o] of Object.entries(st.owned))if(!v.data.items.some(i=>i.id===id)||!Number.isInteger(o.level)||o.level<1||o.level>6)throw Error('存档道具等级无效');const test={...st,placed:[]};for(const p of st.placed){if(!st.owned[p.id]||test.placed.some(q=>q.id===p.id)||!E.validPlacement(test,v.data,p.id,p.x,p.y))throw Error('摆放越界或重叠');test.placed.push(p);}if(st.drawQueue.length)throw Error('请使用已完成三选一的存档');if(!Number.isFinite(st.stamina)||st.stamina<0)throw Error('体力无效');v.data.items.forEach(i=>i.icon=original.items.find(o=>o.id===i.id).icon);data=v.data;state=st;mode=state.mode;history=[];future=[];$('modal').close();render();toast('布局与参数已载入');}catch(err){toast('载入失败：'+err.message);}}
  function download(name,text,type){const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
  function logs(){modal('表演日志',`<p><button id="csv">导出 CSV</button></p><div class="table-wrap"><table><thead><tr><th>场次</th><th>体力</th><th>背包值</th><th>节拍</th><th>节拍加成</th><th>木琴</th><th>魅力</th><th>总分</th><th>效率</th></tr></thead><tbody>${state.logs.map(r=>`<tr><td>${r.number}</td><td>${r.stamina}</td><td>${r.preview}</td><td>${r.totalBeats}</td><td>${pct(r.beatRate)}</td><td>${r.woodAmount}</td><td>${pct(r.charm)}</td><td>${r.total}</td><td>${num(r.total/r.stamina)}</td></tr>`).join('')}</tbody></table></div>`);$('csv').onclick=()=>download('表演日志.csv',[['场次','体力','累计体力','背包值','节拍数','节拍加成','木琴组数','木琴结果','魅力','总分','效率','种子','公式'],...state.logs.map(r=>[r.number,r.stamina,r.spent,r.preview,r.totalBeats,r.beatRate,r.woodGroups,r.woodAmount,r.charm,r.total,r.total/r.stamina,r.seed,r.formula])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv');}
  $('tools').onclick=tools;$('logs').onclick=logs;$('perform').onclick=perform;$('closeModal').onclick=()=>{$('modal').close();if(state.drawQueue.length){rewardFolded=false;render();}};
  $('modal').addEventListener('cancel',()=>{setTimeout(()=>{if(state.drawQueue.length){rewardFolded=false;render();}},0);});
  $('foldReward').onclick=()=>{rewardFolded=true;$('reward').close();$('resumeReward').hidden=false;};$('reward').addEventListener('cancel',e=>{e.preventDefault();$('foldReward').click();});$('resumeReward').onclick=()=>{rewardFolded=false;render();};
  $('unload').onclick=()=>{if(locked())return;checkpoint();previousTotal=E.score(state,data).total;state.placed=[];render();};
  $('undo').onclick=()=>{if(!history.length||locked())return;future.push(snapshot());state=history.pop();render();};$('redo').onclick=()=>{if(!future.length||locked())return;history.push(snapshot());state=future.pop();render();};
  $('expandAll').onclick=()=>{while(state.unlockCredits){let done=false;for(let c=0;c<49;c++)if(E.unlock(state,data,c)){done=true;break;}if(!done)break;}history=[];future=[];render();};
  for(const id of ['search','quality','category','setFilter'])$(id).addEventListener('input',renderInventory);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(state.drawQueue.length){toast('请先完成三选一后切换模式');return;}save();loadMode(b.dataset.mode);});
  $('icons').onclick=()=>modal('表演道具 PNG 资源',`<p>31件独立PNG图标。点击查看原图，可另存为文件。</p><div class="asset-grid">${data.items.map(i=>`<a href="${i.icon}" target="_blank" rel="noopener">${image(i)}${i.name}</a>`).join('')}</div>`);

  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pointerDrag){e.preventDefault();cancelDrag();return;}if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)||$('modal').open||$('reward').open)return;if(e.key==='Backspace'){e.preventDefault();$('unload').click();}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();$('redo').click();}});
  $('setFilter').innerHTML='<option value="">全部套装</option>'+data.sets.map(s=>`<option>${s.name}</option>`).join('');
  $('applyUnlock').onclick=()=>{if(locked())return;try{const n=Number($('unlockCount').value);if(!Number.isInteger(n)||n<9||n>49)throw Error('格数须为9～49');checkpoint();const removed=E.manualUnlock(state,data,n);render();toast('已设为'+n+'格'+(removed.length?'；超出区域道具已回仓':''));}catch(e){toast(e.message);}};
  loadMode(mode);
})();

