const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const E=require('./engine.js');
const D=JSON.parse(fs.readFileSync(path.join(__dirname,'data.json'),'utf8'));
let count=0;function check(name,fn){fn();count++;console.log('OK '+name);}
function state(placed=[]){let s=E.newState(D,'test');s.unlocked=Array.from({length:49},(_,i)=>i);s.placed=placed;return s;}
check('31件，6级基础值，1/3/6技能档位',()=>{assert.equal(D.items.length,31);D.items.forEach(i=>assert.equal(i.base.length,6));assert.deepEqual([1,2,3,4,5,6].map(E.tierIndex),[0,0,1,1,1,2]);});
check('初始中央3x3与固定朝向',()=>{let s=E.newState(D);assert.deepEqual(s.unlocked,[16,17,18,23,24,25,30,31,32]);assert.equal(E.validPlacement(s,D,'P06',2,2),false);for(const p of s.placed)assert(E.validPlacement(s,D,p.id,p.x,p.y));});
check('15体力=6格额度+5次抽奖，两计数器独立',()=>{let s=E.newState(D);E.spend(s,D,15);assert.equal(s.unlockCredits,6);assert.equal(s.drawQueue.length,5);assert.equal(s.drawRemainder,0);assert.equal(s.unlockRemainder,0);assert.equal(s.unlocked.length,9);});
check('保留余数、周期第8次高级、满格停止额度',()=>{let s=E.newState(D);s.stamina=300;E.spend(s,D,4);assert.equal(s.drawRemainder,1);assert.equal(s.unlockRemainder,4);E.choose(s,D,s.drawQueue[0].choices[0]);E.spend(s,D,20);assert.equal(s.drawCount,8);assert.equal(s.drawQueue.at(-1).advanced,true);assert.equal(s.unlockCredits,8);assert.equal(s.unlockRemainder,4);s.drawQueue=[];E.spend(s,D,100);assert.equal(s.unlockCredits,40);assert.equal(s.unlockRemainder,0);});
check('三选一不同品质、候选唯一、品质概率统计',()=>{let normal=[0,0,0,0],advanced=[0,0,0,0],mixed=false;for(let n=1;n<=8000;n++){const draw=E.makeDraw(D,n,'test'+n),q=draw.choices.map(id=>D.items.find(i=>i.id===id).quality);assert.equal(new Set(draw.choices).size,3);if(new Set(q).size>1)mixed=true;for(const x of q)(draw.advanced?advanced:normal)[E.qualities.indexOf(x)]++;}assert(mixed);normal.forEach((n,i)=>assert(Math.abs(n/21000-D.rules.normalWeights[i])<.018));advanced.forEach((n,i)=>assert(Math.abs(n/3000-D.rules.advancedWeights[i])<.025));});
check('奖励结果可复现，未选不能再次消耗',()=>{assert.deepEqual(E.makeDraw(D,8,'same'),E.makeDraw(D,8,'same'));let s=E.newState(D);E.spend(s,D,3);assert.throws(()=>E.spend(s,D,1));});
check('扩格必须相邻，额度不进入抽奖卡',()=>{let s=E.newState(D);E.spend(s,D,5);assert.equal(E.unlock(s,D,0),false);assert.equal(E.unlock(s,D,9),true);assert.equal(s.unlockCredits,1);assert(s.drawQueue.every(d=>d.choices.every(id=>D.items.some(i=>i.id===id))));});
check('古筝3来源、自身及2相邻目标各+3',()=>{const s=state([{id:'P16',x:2,y:2},{id:'P11',x:2,y:1},{id:'P12',x:2,y:4},{id:'P13',x:0,y:6}]);const p=E.score(s,D);assert.equal(p.info.P16.count,3);assert.equal(p.info.P16.ability,3);assert.equal(p.info.P11.ability,3);assert.equal(p.info.P12.ability,8);assert.equal(p.info.P12.sources.find(s=>s.name==='古筝').value,3);assert.equal(p.info.P13.ability,0);assert.deepEqual(p.info.P16.targets,['P16','P11','P12']);});
check('连续管乐链去重，不只直接相邻',()=>{const s=state([{id:'P04',x:0,y:0},{id:'P01',x:2,y:0},{id:'P02',x:2,y:1},{id:'P06',x:2,y:3}]);let p=E.score(s,D);assert.equal(p.info.P04.count,2);assert.equal(p.info.P04.ability,14);});
check('二胡无邻居仍强化自身，中提琴下方为空',()=>{let s=state([{id:'P10',x:0,y:0},{id:'P08',x:3,y:0}]);let p=E.score(s,D);assert.equal(p.info.P10.ability,6);assert.equal(p.info.P08.ability,10);s.placed.push({id:'P22',x:3,y:4});assert.equal(E.score(s,D).info.P08.ability,0);});
check('键盘恰好1件，优雅晚宴至少档，套装不累加',()=>{let s=state([{id:'P17',x:0,y:0},{id:'P14',x:3,y:0}]);let p=E.score(s,D);assert.equal(p.globalPercent,.05);assert.equal(p.sets.find(s=>s.name==='优雅晚宴').tier[1],24);s.placed.push({id:'P18',x:0,y:3});assert.equal(E.score(s,D).globalPercent,0);});
check('装扮OR仅一次、按百分比强化全背包',()=>{let s=state([{id:'P08',x:0,y:0},{id:'P07',x:2,y:0},{id:'P27',x:6,y:6}]);let p=E.score(s,D);assert.equal(p.globalPercent,.003);assert.equal(p.globalSources.filter(x=>x.sourceId==='P27').length,1);assert.equal(p.total,Math.floor(p.subtotal*1.003));});
check('架子鼓按种类去重，木琴按生成拍每3拍转1百分点',()=>{let s=state([{id:'P21',x:2,y:2},{id:'P23',x:1,y:4},{id:'P11',x:2,y:1},{id:'P07',x:0,y:2},{id:'P01',x:4,y:2},{id:'P22',x:4,y:3}]);const p=E.score(s,D);assert.equal(p.extraBeats,4);let result=E.performance(s,D,{beats:8,judgment:'Miss'});assert.equal(result.totalBeats,12);assert.equal(result.beatRate,0);assert.equal(result.woodGroups,4);assert.equal(result.woodPercent,.04);assert.equal(result.total,Math.floor(p.total*1.04));s.owned.P23.level=6;assert.equal(E.performance(s,D,{beats:8}).woodPercent,.16);});
check('魅力加成上限20%，不同阶段不重复累计',()=>{let s=state([{id:'P12',x:0,y:0}]);let a=E.performance(s,D,{seed:'a',charmRatio:1e6});assert.equal(a.charm,.2);assert.deepEqual(E.score(s,D),E.score(s,D));assert.deepEqual(a,E.performance(s,D,{seed:'a',charmRatio:1e6}));});
check('同名两个重复升级，6级封顶',()=>{let s=E.newState(D);s.owned.P12.level=5;for(let i=0;i<3;i++){s.drawQueue=[{choices:['P12']}];E.choose(s,D,'P12');}assert.equal(s.owned.P12.level,6);assert.equal(Object.keys(s.owned).filter(id=>id==='P12').length,1);});
check('实际判定覆盖与生成节拍保持一致',()=>{const s=state([{id:'P23',x:0,y:0}]),opts={seed:'timing',beats:6};const good=E.performance(s,D,{...opts,judgments:Array(6).fill('Perfect')}),miss=E.performance(s,D,{...opts,judgments:Array(6).fill('Miss')});assert.deepEqual(good.beatResults.map(b=>b.quality),miss.beatResults.map(b=>b.quality));assert(good.total>miss.total);assert.equal(good.woodGroups,miss.woodGroups);assert.equal(miss.hits,0);assert.equal(E.judgeTiming(.5),'Perfect');assert.equal(E.judgeTiming(.65),'Great');assert.equal(E.judgeTiming(.8),'Good');assert.equal(E.judgeTiming(null),'Miss');});
check('手动缩格回仓与单件替换判定',()=>{const s=state([{id:'P15',x:0,y:0},{id:'P22',x:1,y:0}]);assert.equal(E.placement(s,D,'P24',0,0).swapId,'P15');assert.equal(E.placement(s,D,'P23',0,0).valid,false);const ids=E.manualUnlock(s,D,9);assert.equal(ids.length,2);assert.equal(s.placed.length,0);assert.equal(s.unlocked.length,9);assert.equal(s.unlockCredits,0);});
console.log(`Completed ${count} numeric checks.`);

